<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Empty the table first
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Project::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        //Define data
        $projects = [
            [
                'user_id' => 1,
                'name' => 'Design interface de gestion',
                //'document'
                'picture' => "1.jpg",
                'about' => "Je suis a la recherche d'un design pour une interface de gestion d'entreprise. Ce projet consiste à réaliser un template de base ainsi qu'une page d'accueil pour une application de gestion de stock. Le thème est la construction et nous disposons déjà de quelques idées mais restons ouvert à toute créativité.",
                'price' => 300,
                'street'=>'Avenue de la couronne',
                'number'=> 127,
                'zipcode'=> 1070,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'0478235690',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-08-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'5',
            ],
            [
                'user_id' => 2,
                'name' => 'Réalisation d\'un coupon de promotion',
                //'document' 
                'picture' => "2.jpg",
                'about' => "Je souhaiterai une réalisation d'un coupon pour faire la promotion de parfum. Je suis propriétaire d'un magain de parfumerie et je souhaiterai réaliser des coupons promotionnels qui seraient offert dans un magazine de mode. Je recherche un graphiste sérieux et dispose de quelques exemples à votre disposition. Nous sommes situés sur Charleroi si vous souhaitez directement me rencontrer. N'hésitez pas à me contacter.",
                'price' => 120,
                'street'=>'Rue de la bonne odeur',
                'number'=> 93,
                'zipcode'=> 45021,
                'country'=>'Belgique',
                'city'=>'Charleroi',
                'phone'=>'049676778',
                'email'=> User::find(2)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'1',
            ],
            [
                'user_id' => 3,
                'name' => 'Mascotte restaurant italien',
                //'document' 
                'picture' => "3.jpg",
                'about' => "Plus qu'un logo, nous souhaiterions une mascotte qui représente une boule de riz italienne, l'Arancini. Un personnage en forme de boule de riz farcie qui donne faim et donne envie de renter dans notre éttablissement. Nous disposons d'un restaurant spécialisé dans l'Arancini sur Bruxelles. Nous sommes ouvert à toute créativité et ne sommes pas pressés... L'idéal serait d'avoir un projet sérieux pour l'année prochaine afin de pouvoir réaliser une nouvelle enseigne et toutes l'identité visuelle du restaurant autour de ce personnage. Merci d'avance.",
                'price' => 850,
                'street'=>'Parkhalenstraat',
                'number'=> 22,
                'zipcode'=> 1850,
                'country'=>'Belgique',
                'city'=>'Grimbergen',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2022-01-01 10:10:10',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'6',
            ],
            [
                'user_id' => 4,
                'name' => 'Flyer combat d\'art-martiaux',
                //'document' 
                'picture' => "4.jpg",
                'about' => "Benthner, le célèbre combattant d'art-martiaux va organiser une rencontre et donc un combat, il aurait besoin d'un flyer afin d'annoncer le prochain évènement. Spécialisé dans les art-martiaux, nous organisons des combats entre célébrités de ce milieu. Merci de nous contacter, personnes sérieuses uniquement ! C'est assez URGENT !",
                'price' => 200,
                'street'=>'Avenue du combattant',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-01 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'1',
            ],
            [
                'user_id' => 5,
                'name' => 'Flyer tournoi d\'art-martiaux',
                //'document'
                'picture' => "5.jpg",
                'about' => "Le célèbre tournoi d'art-martiaux aurait besoin d'un flyer afin d'annoncer le prochain évènement. Spécialisé dans les art-martiaux, nous développons un tournois pour enfant dont voici le projet de flyer pour les cours. L'idée serait de faire un flyer/poster que nous pourrions réutiliser chaque année. Merci de nous contacter, personnes sérieuses uniquement !",
                'price' => 150,
                'street'=>'Avenue du dojo',
                'number'=> 314,
                'zipcode'=> 1830,
                'country'=>'Belgique',
                'city'=>'Strombeek',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-15 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'1',
            ],
            [
                'user_id' => 6,
                'name' => 'Recherche graphiste web',
                //'document'
                'picture' => "6.jpg",
                'about' => "Biblioweb a besoin d'un designer afin de réaliser le design de notre e-shop. Nous sommes une célèbre bibliotheque en ligne connue en europe pour son sérieux et sommes a la recherche d'un rafraichissement de notre enseigne et design. Nous recherchons une personne qualifié uniquement et prete a travailler de concert avec nos développeurs afin de mener ce projet au mieux. A bon entendeur, n'hésitez pas à nous écrire, nous sommes pressés de vous lire ;) Et surtout de vous rencontrer avant de lancer une coopération.",
                'price' => 200,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'5',
            ],
            [
                'user_id' => 7,
                'name' => 'Réalisation d\'un site web',
                //'document'
                'picture' => "7.jpg",
                'about' => "Notre dojo se fait connaitre cependant afin de franchir un nouveau pallier, nous aurions besoins d'un site web ! Nous attendons des propositions sérieuses et pas trop chères ;) Merci de nous contacter ... Voici notre logo pour vous donner une idéee quant au design et couleur de notre futur site ...",
                'price' => 450,
                'street'=>'Avenue de l\'eglise',
                'number'=> 72,
                'zipcode'=> 1000,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'02/850.40.45',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2023-12-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'10',
            ],
            [
                'user_id' => 8,
                'name' => 'Référencement site web centre médical',
                //'document'
                'picture' => "8.jpg",
                'about' => "Notre centre médical dispose d'un site web réalisé avec le CMS Drupal et est mal placé dans Google. Nous recherchons des personnes qualifiées afin d'être présent dans la première page car actuellement en deuxième. Nous disposons de moyens et souhaiterions travailler sur le long terme ensemble car disposons également d'un autre site. A bon entendeur, nous voulons aussi avoir des résultats rapidement. Merci de nous contacter.",
                'price' => 1500,
                'street'=>'Avenue du Kolenbeek',
                'number'=> 236,
                'zipcode'=> 1080,
                'country'=>'Belgique',
                'city'=>'Molenbeek',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'12',
            ],
            [
                'user_id' => 9,
                'name' => 'Application de réservation mobile de croisière',
                //'document'
                'picture' => "9.jpg",
                'about' => "Nous organisons des croisières de luxe. Besoin d'une app de réservation de places pour compléter nos cruises incomplets. Nous aurions besoin de cette application pour l'année à venir. Vous pouvez toujours vous rendre sur notre site web : www.levezlancre.be pour avoir une idée de notre design et notre standing.",
                'price' => 4000,
                'street'=>'Avenue de l\'ancre',
                'number'=> 6,
                'zipcode'=> 5600,
                'country'=>'Belgique',
                'city'=>'Ostende',
                'phone'=>'02/800.76.76',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2022-02-01 16:33:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'9',
            ],
            [
                'user_id' => 10,
                'name' => 'Réalisation carte de visite',
                //'document'
                'picture' => "10.jpg",
                'about' => "Besoin d'une carte de visite pour notre entreprise. Nous comptons 9 personnes au total et aurions besoin d'une carte devisite pour chacune d'entre elle. Vous pouvez consulter notre site web pour vous procurer notre logo et avoir une idéee de nos réalistations sur : www.mvc.com. Rien ne presse pour ce projet mais nous souhaiterions avoir notre mot à dire sur le design afin de guider au mieux le graphiste.",
                'price' => 150,
                'street'=>'Avenue du ruisseau',
                'number'=> 23,
                'zipcode'=> 54730,
                'country'=>'Luxembourg',
                'city'=>'Luxembourg',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2023-05-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'2',
            ],
            [
                'user_id' => 11,
                'name' => 'Réalisation de carte de visite',
                //'document'
                'picture' => "11.jpg",
                'about' => "Mon entreprise nécessite une dizaine de cartes de visites, voici un appercu de l'ancienne mais entre temps nous avons changé de logo.",
                'price' => 180,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'2',
            ],
            [
                'user_id' => 12,
                'name' => 'Carte de visite Urgent',
                //'document'
                'picture' => "12.jpg",
                'about' => "Nous avons besoin assez rapidement de cartes de visites recto-verso avec le logo de la société. Nous sommes installés sur Paris et Bruxelles.",
                'price' => 260,
                'street'=>'Avenue du Chene',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'2',
            ],
            [
                'user_id' => 13,
                'name' => 'Design carte de visite',
                //'document'
                'picture' => "13.jpg",
                'about' => "J'aurai besoin de cartes de visites avec le logo de mon entreprise. Je travaille dans le batiment et je dispose déjà d'un logo.",
                'price' => 100,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-12-05 10:20:52',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'2',
            ],
            [
                'user_id' => 14,
                'name' => 'Peinture murale',
                //'document'
                'picture' => "14.jpg",
                'about' => "Je recherche un peintre qui pourrait réaliser un beau dessin dans la chambre de mon fils. Le thème serait sur les pirates. Merci beaucoup.",
                'price' => 130,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-12-06 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'6',
            ],
            [
                'user_id' => 15,
                'name' => 'Fresque footbal',
                //'document'
                'picture' => "15.jpg",
                'about' => "Il nous faudrait un artiste capable de peindre un footballer sur un mur d'une chambre. Voici un exemple de ce que nous souhaitons.",
                'price' => 200,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-12-05 10:19:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'6',
            ],
            [
                'user_id' => 16,
                'name' => 'Peinture animaux',
                //'document'
                'picture' => "16.jpg",
                'about' => "Pour l'anniversaire de ma fille, nous aimerions lui offrir une peinture murale dans sa chambre avec des animaux comme sur l'image ci-jointe.",
                'price' => 300,
                'street'=>'Avenue du ruisseau',
                'number'=> 25,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 10:10:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'6',
            ],
            [
                'user_id' => 16,
                'name' => 'Réalisation d\'un site web vitrine',
                //'document'
                'picture' => "17.jpg",
                'about' => "Je recherche quelqu'un qui serait en mesure de réaliser un site web vitrine pour ma société. Le site se doit d'être simple et ne contiendrait que quelques pages.",
                'price' => 1200,
                'street'=>'Avenue du cirque',
                'number'=> 7,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-12-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'10',
            ],
            [
                'user_id' => 1,
                'name' => 'Site web pour cabinet médical',
                //'document'
                'picture' => "18.jpg",
                'about' => "Nous avons besoin d'un site web pour notre cabinet médical, le site se doit d'être effcicace et doit posséder un agenda afin de prendre des réservations.",
                'price' => 2500,
                'street'=>'Avenue du fleuve',
                'number'=> 87,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-09-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'12',
            ],
            [
                'user_id' => 2,
                'name' => 'Référencement de notre site',
                //'document'
                'picture' => "19.jpg",
                'about' => "Notre site web étant mal positionné sur les moteurs de recherches, je recherche quelqu'un pour le placer au plus haut possible, idéalement sur la page une biensur ! :).",
                'price' => 600,
                'street'=>'Avenue du buisson',
                'number'=> 192,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2022-09-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'12',
            ],
            [
                'user_id' => 11,
                'name' => 'Réalisation d\'un livre media',
                //'document'
                'picture' => "20.jpg",
                'about' => "Besoin d'un livre média dans le même thème que notre site web, afin de présenter notre catalogue aux clients. Merci de nous contacter pour davantage d'information !",
                'price' => 900,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2022-09-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'4',
            ],
            [
                'user_id' => 1,
                'name' => 'Réalisation d\'un livre media',
                //'document'
                'picture' => "21.jpg",
                'about' => "Ensemble de projets au choix, rejoingnez nos équipes de designers au plus vite. Nous sommes installés sur Paris et Bruxelles.",
                'price' => 200,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-12-05 10:10:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'9',
            ],
            [
                'user_id' => 6,
                'name' => 'Application de rendez-vous pour mobile.',
                //'document'
                'picture' => "22.jpg",
                'about' => "Nous souhaiterions une app mobile permettant aux utilisateurs de planifier leurs rendez-vous au sein de notre agence. Nous sommes une agence de location de matériel sono.",
                'price' => 4300,
                'street'=>'Rue du violon',
                'number'=> 651,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-11-05 11:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'9',
            ],
            [
                'user_id' => 15,
                'name' => 'Correction de bugs PHP',
                //'document'
                'picture' => "23.jpg",
                'about' => "Notre site construit avec un CMS PHP rencontre de nombreux bugs et nous souhaiterions bénéficier des services d'un expert pour nous conseiller et corriger ces problèmes.",
                'price' => 80,
                'street'=>'Avenue sans issue',
                'number'=> 1,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2022-12-05 10:20:54',
                'done'=> NULL,
                'category_id' =>'2',
                'sub_category_id' =>'11',
            ],
            [
                'user_id' => 16,
                'name' => 'Design carte de visite',
                //'document'
                'picture' => "24.jpg",
                'about' => "Nous sommes installés sur Paris et Bruxelles et nous recherchons un design pour une carte de visite. Voici un appercu du style de carte souhaitée.",
                'price' => 110,
                'street'=>'Rue du chateau',
                'number'=> 9,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-10-20 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'2',
            ],
            [
                'user_id' => 13,
                'name' => 'Réalisation d\'un template web',
                //'document'
                'picture' => "25.jpg",
                'about' => "Ensemble de projets au choix, nous recherchons des designeurs qualifiés pour réaliser de temps à autres des templates pour site web.",
                'price' => 200,
                'street'=>'Avenue du ruisseau',
                'number'=> 22,
                'zipcode'=> 10427,
                'country'=>'Belgique',
                'city'=>'Bruxelles',
                'phone'=>'049676778',
                'email'=> User::find(1)->email,
                'notifications' => 0,
                'rules' => true,
                'created_at'=> '2021-07-04 08:06:44',
                'updated_at'=> '2021-07-05 10:20:54',
                'deadline'=> '2021-10-20 10:20:54',
                'done'=> NULL,
                'category_id' =>'1',
                'sub_category_id' =>'5',
            ],
        ];
        //Insert data in the table

        foreach ($projects as $data) {
            DB::table('projects')->insert([
                'user_id' => $data['user_id'],
                'name' => $data['name'],
                //'document' => $data['document'],
                'picture' => $data['picture'],
                'deadline' => $data['deadline'],
                'about' => $data['about'],
                'created_at' => $data['created_at'],
                'updated_at' => $data['updated_at'],
                'done' => $data['done'],
                'price' => $data['price'],
                'street'=> $data['street'],
                'number'=> $data['number'],
                'zipcode'=> $data['zipcode'],
                'country'=> $data['country'],
                'city'=> $data['city'],
                'phone'=> $data['phone'],
                'email'=> $data['email'],
                'notifications' => $data['notifications'],
                'rules' => $data['rules'],
                'category_id' => $data['category_id'],
                'sub_category_id' => $data['sub_category_id'],
            ]);
        }
    }
}
